apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: strimzi-connect-cluster-custom-image
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: entechlog/strimzi-kafka-connect:2
  version: 2.6.0
  replicas: 1
  bootstrapServers: 192.168.1.15:39092
  config:
    group.id: strimzi-connect-cluster-custom-image
    offset.storage.topic: strimzi-connect-cluster-custom-image-offsets
    config.storage.topic: strimzi-connect-cluster-custom-image-configs
    status.storage.topic: strimzi-connect-cluster-custom-image-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
  externalConfiguration:
    volumes:
      - name: connector-config
        secret:
          secretName: connect-secrets